gramener/gramex

tests/test_formhandler.py
Ref to bug introduced due to !64
=> BUG: FormHandler edits should adhere to existing types

gramex/__init__.py, gramex/gramex.yaml
- Allows user to disable watching `gramex.yaml`, which disables autoreloading `gramex.conf` via `gramex --nowatch`
- Also, provides `gramex.init(watch=True)` to explicitly not watch files.
=> ENH: --watch=False / init(watch=False) disables autoreloading gramex.yaml

gramex/apps/guide/cache/README.md, gramex/apps/guide/formhandler/README.md, gramex/cache.py
parquet, feather formats are useful to read processed dataframes faster.
=> ENH: FormHandler, cache.open support for parquet, feather

gramex/apps/nlg/__init__.py, gramex/apps/nlg/gramex.yaml, gramex/apps/nlg/grammar.py, gramex/apps/nlg/grmform.html, gramex/apps/nlg/index.html, gramex/apps/nlg/nlgapp.py, gramex/apps/nlg/nlgsearch.py, gramex/apps/nlg/nlgutils.py, tests/test_nlg.py
@jaidevd Gramex adds app paths to sys.path. This means that module names like `utils` are importable via "import utils". But many apps already do this. For example, gramex/tests uses a utils.py. uat.gramener.com has a few apps that use utils.py. 
I've sent a PR that renames utils.py to nlgutils.py, and a few other modules. Is this fine? If yes, and if it doesn't break other stuff, please merge into dev.
=> BUG: rename NLG modules to avoid conflict

.gitlab-ci.yml, .travis.yml, gramex/apps/nlg/setup.sh
The spacy model dependency didn't exist in .gitlab-ci.yml - adding that.
=> Fix spacy dependencies

gramex/apps/guide/formhandler/README.md, gramex/apps/guide/formhandler/vega-lite.yaml, gramex/apps/guide/formhandler/vega.yaml, gramex/data.py, gramex/handlers/formhandler.py, tests/test_formhandler.py, tests/vega-lite.yaml, tests/vegam.yaml
- Supports substitution of URL args  in vega spec recursively.
- Supports default values
- `<script src="vega-lite-1?_format=barchart&CHART_TYPE=line&CHART_Y=c4"></script>` draws `line` chart with `c4` as `y` metric
- `<script src="vega-lite-1?_format=barchart"></script>` draws `bar` chart with y as `c1` 
```
url:
formhandler-vega-lite-1:
pattern: /$YAMLURL/vega-lite-1
handler: FormHandler
kwargs:
url: $YAMLPATH/flags.csv
function: data.groupby('Continent').sum().reset_index()
default:
CHART_TYPE: bar
CHART_Y: c1
formats:
barchart:
format: vega-lite
spec:
"$schema": "https://vega.github.io/schema/vega-lite/v2.json"
width: 400
height: 200
autosize:
type: fit
contains: padding
mark: '{CHART_TYPE}'
encoding:
x: {field: Continent, type: ordinal}
y: {field: '{CHART_Y}', type: quantitative}
```
=> ENH: Vega spec substitute url args #99

gramex/pptgen/commands.py
```
pptxhandler/table-example2:
pattern: /$YAMLURL/table-example2
handler: PPTXHandler
kwargs:
headers:
Content-Disposition: attachment; filename=table-example.pptx
only: 10
source: $YAMLPATH/examples-input.pptx  # Common example file
data:
table_data: {url: $YAMLPATH/sales.csv}
new-edit-table:
Table 1:                      # Shape Name
table:
data: data['table_data']
style:                    # Common CSS for all the cells
font-size: 14
text-align: center
italic: True
underline: True
columns:
1:                  # Common CSS will get over-write for Sales column
gradient: Reds
2:
gradient: Greens
5:
gradient: Blues
0:            # Common CSS will get over-write for GrossProfit column
bold: False
underline: False
italic: False
```
=> ENH: pptgen table column can be positional identifiers

gramex/handlers/authhandler.py
user can pass kwargs containing user_id.
- Likelihood for user's auth data containing  `_user_id` over `user_id` is less.
- Also, document not to have column named `_user_id`?
=> REF: Use _user_id argument for update_user

.travis.yml, Makefile, setup.cfg, setup.py, testlib/test_pptgen.py, testlib/test_r.py, tests/__init__.py, tests/gramex.yaml, tests/requirements.txt, tests/test_filehandler.py, tests/test_schedule.py, tests/utils.py
I've made the following changes:
1. When Gramex ran any test, it used to run a brittle TestSchedule that assumed that Gramex would start in 10 seconds, and ensured that nosetests runs for at least 10 seconds. This is refactored. **BENEFIT**: `nosetests test.test_functionhandler` and similar sub-tests run quicker
2. I've replaced `tests_require` with `tests/requirements.txt`. The former doesn't accept nose plugins. So now, we run `make test-setup` or `pip install -r tests/requirements.txt` before any tests
=> WIP: Fast test

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Users can choose three templates for submitting issues - bug reports,
feature requests, and a blank one. They contain checklists to ensure
reproducibility. The PR template contains a checklist
for users to ensure that patches can be reproduced and reviewed easily.
=> ENH: Add issue and PR templates

pkg/conda/template.meta.yaml
The latest nodejs version available under conda-forge is not stable,
which causes this error:
https://stackoverflow.com/questions/64612707/node-sass-does-not-yet-support-your-current-environment-windows-64-bit-with-uns
=> REQ: Restrict nodejs to LTS versions

.gitignore, gramex/apps/forms/form.html, gramex/apps/forms/form_builder.py, gramex/apps/forms/gramex.yaml, gramex/apps/forms/style.scss
forms.db and analytics, forms tables need to be created before forms app can be used.
- introduce [formhandler](https://learn.gramener.com/guide/formhandler/#formhandler-columns) columns-based table creation for `analytics` and `forms` tables
- downstream impact: update data-source for `.formhandler()` in form.html
- disable mouse events while previewing the form at `/form/id`
-  add a prominent way to View form in addition to a link in navbar 
Without this, forms app wouldn't work.
=> Initialize tables on first load in forms 

gramex/handlers/mlhandler.py, tests/test_mlhandler.py
Rendering any template in MLHandler accidentally drops the target
column. Fixing this. Closes #361
=> FIX: Viewing an MLHandler template drops the target col

gramex/handlers/websockethandler.py
We're accidentally checking for `domain.netloc`, where domain is a string.
=> BUG: Fix origin check in WebSocketHandler

pkg/conda/template.meta.yaml, pkg/docker-py3/Dockerfile.tmpl
1. Gramex >=1.67 requires git lfs on the build machine. Specifying git sources in the conda recipe breaks it. Use local path for the source instead.
2. In the Dockerfile, pin miniconda3 version to the latest one that has Python 3.7 in the base env.
=> BLD: Use local source for conda; fix miniconda version for Docker

gramex/handlers/mlhandler.py, tests/test_mlhandler.py
Required for fixing #377
Since v0.24, sklearn's column transformers need the same order of
feature names between .fit and .predict. We can still send URL
parameters in any order, but they need to be ordered correctly by the
MLHandler. See sklearn's release notes for more:
https://scikit-learn.org/stable/whats_new/v0.24.html#sklearn-compose
=> FIX: Enforce correct order of features before prediction in MLHandler

gramex/handlers/mlhandler.py
MLHandler doesn't respect any auth config. This PR fixes that.
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-99)
=> GRAMEX-99 ⁃ FIX: Allow auth for MLHandler

gramex/apps/admin2/gramex.yaml, gramex/apps/admin2/gramexadmin.py, gramex/apps/admin2/index.html, gramex/handlers/basehandler.py
This PR allows admins to:
1. Add users with passwords, and send welcome emails to them, when the `forgot` key in DBAuth is present.
1. Filter users on any attribute (`pd.Series.str.contains`), and change their attributes.
This currently works only on DBAuth. sanand0 Please take a look.
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-89)
=> GRAMEX-89 ⁃ Admin page enhancements

gramex/data.py
Pass all the expected arguments to ignore unexpected arguments in kwargs to pd.io.sql.to_sql
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-118)
=> GRAMEX-118 ⁃ FIX: Pass all the expected arguments to pd.io.sql.to_sql

gramex/apps/admin2/gramexadmin.py
When an `authhandler:` is specified in an Admin2 user management spec, `AdminFormHandler` picks up the corresponding user attributes in a way that does not work with nested apps.
This PR fixes that.
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-119)
=> GRAMEX-119 ⁃ BUG: Ensure that user management with rules works in nested apps

gramex/data.py
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-125)
=> GRAMEX-125 ⁃ FIX: Don't mention InfluxDB buckets in URLs

gramex/handlers/mlhandler.py
This patch fixes MLHandler tests on:
* Python 3.8
* Numpy 1.22.1
* Pandas 1.3.5
See: https://github.com/gramener/gramex/issues/300#issuecomment-1015009631
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-143)
=> GRAMEX-143 ⁃ FIX: MLHandler for Py 3.8, pandas 1.x

gramex/handlers/mlhandler.py, tests/test_mlhandler.py
Note: this works only with pandas==1.4.x
See https://github.com/pandas-dev/pandas/blob/main/pandas/io/excel/_base.py#L806
The append mode for `pd.ExcelWriter` or `df.to_excel` works only when writing to new sheets. Appending to existing sheets needs a new param (`if_sheet_exists="overlay"`) which was introduced only in Pandas v1.4
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-147)
=> GRAMEX-147 ⁃ Store MLHandler data in Excel

gramex/handlers/basehandler.py, gramex/transforms/auth.py, tests/gramex.yaml, tests/test_auth.py, tests/utils.py
This addresses #434 partially. Calling `handler.apikey(expiry)` generates an API key with the same info as the logged-in user. By default, the key expires after 1e9 seconds ~ 32 years. Any request with a `?gramex-key=<apikey>` or header `X-Gramex-Key: <apikey>` will log in as that user.
Created by radheyakale
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-164)
=> GRAMEX-164 ⁃ Create and use Gramex API key

gramex/apps/mlhandler/template.html, gramex/handlers/mlhandler.py, gramex/ml_api.py, gramex/sm_api.py, tests/gramex.yaml, tests/requirements.txt, tests/test_mlhandler.py
Post https://github.com/gramener/gramex/pull/507, this version of the statsmodels API is available via the
wrapper classes for MLHandler, instead of being in the handler itself.
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-175)
=> GRAMEX-175 ⁃ ENH: Add support for statsmodels.SARIMAX in MLHandler

pkg/docker-py3/Dockerfile.tmpl
Fixes #448
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-88)
=> GRAMEX-88 ⁃ FIX: Allow releaseinfo change in Docker conda image

gramex/transforms/transforms.py, tests/gramex.yaml, tests/test_functionhandler.py
build_transform() compiles a string into a function.
build_transform(iter=True) forces the function to return an array.
Last week, we modified build_transform() to compile pipelines.
(Pipelines = ARRAYS of functions.)
But it didn't support iter=True.
It always returned the value as-is.
(Why? I didn't think it would be needed.)
But there's a reason why iter=True is there in build_transform.
FunctionHandler requires iterables.
This lets it render functions that yield values one by one, slowly.
So, build_transform() needs to support iter=True even for
ARRAYS of functions, i.e. pipelines.
Now, build_transform() now supports iter=True for pipelines.
It just returns the output as an array (or as-is, if it's a generator.)
This apart, there's another change.
Earlier, pipeline steps had to be …
=> GRAMEX-195 ⁃ FIX: Pipelines support iter=True

gramex/transforms/template.py, tests/test_filehandler.py
RMarkdown is rarely used with Gramex. It is very hard to support.
The underlying packages have several installation issues and
compatibility issues with NumPy. So we're phasing out support.
=> DEP: rmarkdown deprecated in FileHandler transforms

tests/test_capturehandler.py
PhantomJS is deprecated. There's no point testing it any more.
If PhantomJS is not installed, the tests should not fail.
=> TST: If PhantomJS is not installed, skip capture tests

gramex/apps/logviewer/logviewer.py
* Indexing time column removed from logviewer as time is required as a column
=> FIX: Indexing time column removed from logviewer

gramex/handlers/basehandler.py, tests/gramex.yaml, tests/test_auth.py, tests/utils.py
handler.revoke_otp(otp) revokes the OTP.
handler.revoke_apikey(key) revokes the API key.
=> ENH: Allow revoking OTP and API keys

gramex/apps/ui/__init__.py, tests/test_filehandler.py
FileHandler compiles .sass, .scss, .ts, .vue files to CSS/JS.
When generating CSS/JS, these create source maps.
To expose the source maps via FileHandler using the same extension, we add `?_map`. For example:
- The source map for `a.ts` is at `a.ts?_map`
- The source map for `a.scss?color=red` is at `a.scss?color=red&_map`
=> ENH: Enable SASS sourcemaps. Use ?_map=

gramex/gramex.yaml, gramex/services/__init__.py
storelocations.otp needs to be purged of expired keys.
This was handled by a daily schedule.
But this schedule uses time.time() to get the current time.
That requires the time module to be imported first.
(Gramex transforms auto-import only modules at the start.)
So, refactor the purge code into a function.
=> FIX: storelocations.otp purge now works

gramex/handlers/__init__.py, gramex/handlers/mlhandler.py, tests/gramex.yaml, tests/test_mlhandler.py, tests/titanic.csv, tests/utils.py
MLPredictor takes a FormHandler-like dataset spec and makes prediction on each row, given a sklearn model. FormHandler filters can be applied to datasets as usual.
=> ENH: MLPredictor runs ML predictions on FormHandler datasets

gramex/data.py, testlib/test_data.py
Earlier, comparison was via a string. That works for YYYY-MM-DD formats but not for other formats.
=> FIX: FormHandler converts date values before comparing

gramex/handlers/basehandler.py, tests/test_handlers.py
We can't use the Origin: header to check if it's XSRF. Nor just the presence of a Sec-Fetch-* header. Browsers send these headers on a form POST too. Checking specifically for Sec-Fetch-Mode=cors seems to work fine, though.
=> BUG: Use Sec-Fetch-Mode=cors to detect fetch for XSRF

tests/functionutils.py
Line 37, 38 of the file `tests/functionutils.py` uses a loop to concatenate strings. 
I think the more pythonic way is to use `str.join` instead. 
On the performance level, `str.join` is much faster if the list is very long.
=> Dissolve a for loop that concatenate strings to str.join

gramex/gramex.yaml, gramex/handlers/basehandler.py, gramex/transforms/__init__.py, gramex/transforms/transforms.py, tests/gramex.yaml, tests/test_handlers.py
Every handler supports rate-limiting via `ratelimit:`. For example:
```yaml
url:
page:
pattern: /api
handler: FormHandler # or any handler
kwargs:
ratelimit:
keys: [daily, user.id]
limit: 50
```
`keys` define how to rate-limit. It's an array of strings, or a comma-separated list of strings:
```yaml
keys: [weekly, user]
keys: weekly, user  # same as above
keys: [daily]
```
The strings can be:
- Time-based keys
- `hourly`: Reset limit every hour (UTC)
- `daily`: Reset limit every day (UTC)
- `weekly`: Reset limit every week, starting Sunday (UTC)
- `monthly`: Reset limit every month, starting 1st of the month (UTC)
- `yearly`: Reset limit every month, starting 1-Jan (UTC)
- Any key from the [logging config](https://gramener.com/gramex/guide/config/#request-logging), e.g.
- `user`: The …
=> ENH: API ratelimit available for all handlers. Fixes #632

gramex/data.py, gramex/release.json
Only InfluxDB requires this, we'll handle it later if needed.
Closes #636
=> REQ: Remove tzlocal as a dependency

gramex/config.py, gramex/data.py, gramex/transforms/transforms.py, testlib/test_data.py, tests/test_filterhandler.py, tests/test_openapihandler.py
Earlier, FilterHandler used in_memory= only for SQLAlchemy data stores. Now it works for all stores by running a `gramex.data.filter` on the superset of required data, and filtering the rest in memory.
Also, fixed a bug where duplicate column names raised an error. @umang1995 -- this should fix your issue.
=> FIX: FilterHandler in-memory works for all types of DBs

.gitignore, pkg/usage/gramexsize.py, pkg/usage/gramexsize.yaml, pyproject.toml, reports/gramexsize.csv, reports/loc.csv, task
This creates a `reports/gramexsize.csv` that shows cyclomatic complexity of Gramex features.
`gramexsize.yaml` has a `code2yaml`. It maps
- from Python wildcard paths (e.g. modules like `gramex.cache.*` or methods like `gramex.handlers.basehandler.BaseMixin.setup`)
- to YAML wildcard paths (e.g. `url.*.handler=FormHandler|FilterHandler|MLHandler|DriverHandler`)
It calculates the complexity of the Python paths, and saves it along with the YAML paths in `reports/gramexsize.csv`.
In a project, we can match the YAML paths used, and calculate the corresponding Python complexity. This gives us the complexity of the Gramex features used.
=> BLD: Compute Gramex feature size & complexity

gramex/handlers/openapihandler.py, tests/gramex.yaml, tests/test_openapihandler.py
If a FunctionHandler has only a POST method, the code auto-adds a GET with a summary. (Because we do that by default for all handlers.)
This commit fixes that.
We were also updating the DEFAULT OpenAPI specs with each handler's specs. So the specs were over-writing each other.
Now we make a copy of the spec before updating it.
=> FIX: OpenAPIHandler spec for FunctionHandler supports POST-only

gramex/services/__init__.py
If app.listen.port is specified as a string,
logging tried to parse it as an integer and fail.
Now accept strings and numbers
=> FIX: allow listen.port to be a number

gramex/data.py, pytest/dbutils.py, pytest/test_data.py, testlib/test_data.py
gramex.data.delete now works exactly like .filter(). It deletes all rows that match a query.
The earlier behavior was to delete only specified IDs.
=> FIX: gramex.data.delete works without id. Fixes #662

gramex/gramex.yaml
By default, FileHandler ignores files/folders beginning with `.`.
Conda installs non-root environments in a .conda folder.
If Gramex is installed in a non-root environment,
app-related files like logviewer's index.html won't be displayed.
This PR allows any gramex/apps/ files under a .conda folder.
The `allow:` is very specific to expose as few files are possible.
=> FIX: FileHandler permits Gramex apps files under .conda

gramex/cache.py, gramex/data.py, gramex/handlers/filterhandler.py, gramex/handlers/formhandler.py, pytest/test_data.py, testlib/test_data.py, tests/test_formhandler.py
- ENH: argstype: converts URL args to Python types in SQL params
- ENH: argstype: supports expanding=True to bind iterable SQL params
- API: gramex.data.{update,delete,insert} use positional args before meta
- REF: data.{filter,update,delete,insert} have consistent signatures
- REF: Use data._convertor() for all internal type conversions
- REF: gramex.cache uses a single JSON dump with CustomJSONEncoder
- FIX: support filtering string columns that has NaN/NULL
- REF: improve type checking
=> ENH: gramex.data.* functions accept argstype to typecast args

gramex/handlers/filterhandler.py, testlib/test_cache_module.py
On a completely unrelated note, 0c5fd292 refactored the cache keys. Change the test case to reflect that.
This cache key change is (likely) a harmless, and might only require a restart. But need to keep an eye on this.
=> FIX: FilterHandler overridden method should RETURN something!

gramex/gramex.yaml, gramex/handlers/authhandler.py, gramex/migrate.py, tests/test_auth.py
Instead of hard-coding where user data is stored, we allow developers to specify a storelocations.user in gramex.yaml.
This helps with distributed Gramex instances that need to pick up user info from a different server, not a local SQLite DB
=> ENH: Allow developers to specify user store location. Fixes #655

.gitlab-ci.yml, gramex/migrate.py
Gramex 1.87.0 requires migrating storelocation.user (auth.user.db) schema. We used BLOB earlier for SQLiteStore. We're moving to FormHandler, which requires TEXT.
Gramex 1.87.0 migrates the SQLite database to TEXT.
But the code was tested on Windows, not UNIX. On UNIX, the migration fails because the path comparison uses a different separator.
This commit fixes the issue.
=> FIX: migration works on UNIX. Fixes #677

gramex/data.py, gramex/handlers/basehandler.py, pytest/test_data.py
- gramex.data.alter is efficient due to caching
- clarify X-Gramex-User behavior
- explain why we need to ping Postgres in tests
=> DOC: Minor code documentations

gramex/gramex.yaml, gramex/services/__init__.py
This lets developers use PYTHONBREAKPOINT=ipdb.set_trace or any other callable.
See https://peps.python.org/pep-0553/
=> ENH: Allow any debugger vai breakpoint() not pdb.set_trace()

gramex/migrate.py, gramex/services/scheduler.py, gramex/transforms/transforms.py
Earlier, schedules printed a single line exception summary. Now, schedule exceptions show the full traceback.
Also, pipelines log exception info into a SQLite database. But this itself can fail. Capture and log that, but don't raise.
=> FIX: schedules log full exception. Pipelines ignore logging errors

gramex/handlers/commenthandler.py
Earlier, CommentHandler required an 'id' field for delete. The PUT method required args inside a 'data' field. Now, we've flattened it. args are used as is and processed using the ['_method'] key.
=> FIX: CommentHandler updates/deletes on flat args structure

gramex/handlers/basehandler.py, tests/gramex.yaml, tests/test_handlers.py
This is useful for programmatically checking the number of requests remaining for the URL.
=> ENH: handler.get_ratelimit() returns ratelimit info

gramex/handlers/403.html
If handler.current_user has any non-YAML-encodable object, the HTTP 403 template currently fails.
This commit captures any YAML dump exception, and instead just prints repr(handler.current_user) as an alternative.
=> FIX: HTTP 403 template works with any user object. Fixes #731

gramex/gramex.yaml, gramex/handlers/basehandler.py, tests/gramex.yaml, tests/test_auth.py, tests/utils.py
OTPs and API keys store a user object as JSON. You can add additional keys to this object with this configuration.
```yaml
storelocations:
otp:
columns:
role: TEXT
group: TEXT
```
The `columns:` are specified like [FormHandler columns](https://gramener.com/gramex/guide/formhandler/#formhandler-columns).
You can populate these columns using keyword arguments to `handler.otp()` and `handler.api_key()`
```python
handler.otp(user={"id": "alpha"}, role="admin", group="all")
handler.api_key(user={"id": "alpha"}, role="admin", group="all")
```
When the user logs in with the OTP or API key, the user object will be
```json
{"id": "alpha", "role": "admin", "group": "all"`}
```
Of course, this could also be written as
```python
handler.otp(user={"id": "alpha", "role": "admin", "group": "all"`})
``` …
=> ENH: add extra columns to storelocations.otp. Fixes #736

gramex/handlers/basehandler.py, gramex/handlers/formhandler.py, tests/test_drivehandler.py
Earlier, FormHandler parsed JSON body inside the `post()`, `put()` or `delete()` methods.
`self.args` in subclasses like DriveHandler don't have the JSON body in it until these methods are called, which is sometimes too late (e.g. if we want to do something BEFORE delete.)
This commit moves the JSON body parsing into the `prepare()` method which is called first.
=> FIX: DriveHandler supports JSON body for PUT/DELETE. Fixes #738

gramex/services/emailer.py
Earlier, even if mailer.mail(from=) was provided, it would not override the email service default email: config as the sender.
But this creates a problem with SES, which requires the IAM as the email: in the email service.
This commit allows the from= to override the email sender.
NOTE: This means that we cannot specify a different From: than sender.
=> FIX: mailers use From: as sender if provided. Fixes #752

gramex/handlers/basehandler.py
When overriding users, custom keys override the user object. But if the user object has a key (e.g. email) and it's ALSO a custom key that is not set, the NULL value should NOT override the value set in the user object.
This specifically affects EmailAuth.
=> FIX: null OTP custom keys won't override. Fixes #759
