gramener/gramex

gramex/apps/guide/markdown.template
Adding Quickstart guide link to Left Navigation Bar.
=> DOC: Update markdown.template. Fixes #72

gramex/apps/capture/chromecapture.js, gramex/apps/guide/capturehandler/README.md, gramex/apps/init/.eslintrc.js, gramex/handlers/capturehandler.py, tests/dir/capture.html, tests/test_capturehandler.py
Adds functionality for header and footer with documentation and a testcase
=> Headerfooter

gramex/apps/nlg/search.py, gramex/apps/nlg/utils.py, gramex/apps/nlg/webapp.py, tests/test_nlg.py
Makes NLG work with Python 2 and 3. On this branch, when running tests with Py2, nothing breaks because of Python version mismatch.
=> Python 2 fixes

gramex/apps/guide/guide.py
Markdown frontmatter should be cache along.
=> BUG: markdown meta should be cached

gramex/apps/ui/package.json, gramex/apps/ui/yarn.lock
Fixes #138 , upgrade to vega-lite@3 stable release, leaflet@1.4
=> ENH: UI upgrade bootstrap-select@1.13.8 leaflet@1.4 vega-lite@3

gramex/apps/guide/formhandler/README.md, gramex/data.py, testlib/test_data.py
=> ENH: FormHandler support column aggregations. See #145

pkg/docker-py3/Dockerfile, pkg/docker-py3/README.md
Built image is 2.7Gb, roughly half the size of the Anaconda based image. 
partially solves #81 @sanand0 should I add images for gramexenterprise and gramex dev?
=> Dockerfile updated to miniconda

gramex/ml.py, setup.py
=> REF: add joblib dependency, load sklearn on demand #188

pkg/docker-py3/Dockerfile.tmpl, pkg/docker-py3/build.py
=> BLD: Update Dockerfile to install gramex from conda

.gitlab-ci.yml, Makefile, pkg/build_conda.sh, pkg/build_pypi.sh
@sanand0 Please let me know when you push this to Gitlab. If the pipeline succeeds, we can change the branch names in the build stages.
=> BLD: Add an auto-build script for PyPI and conda

gramex/apps/uifactory/create.html, gramex/apps/uifactory/js/script.js, gramex/apps/uifactory/modals/add-field.html
- disable form loading from localStorage for a new form
- placeholders for form name and description
- search fields in Modal
- Create/Update text change
related issue: #395
=> UIFactory text and form creation changes

gramex/apps/mlhandler/template.html
=> ENH: Replace MLHandler's default template

gramex/apps/logviewer/gramex.yaml, gramex/apps/logviewer/logviewer.py
* Backend support added for Custom Logging
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-96)
=> GRAMEX-96 ⁃ GRAMEX-77 - Apps: Log Viewer (#453)

gramex/release.json, pkg/conda/template.meta.yaml
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-117)
=> GRAMEX-117 ⁃ BLD: Avoid upgrading to sklearn v1.0

MANIFEST.in
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-141)
=> GRAMEX-141 ⁃ BLD: Include servicenow.yaml in the MANIFEST

gramex/apps/mlhandler/template.html, gramex/handlers/mlhandler.py, gramex/ml_api.py, tests/gramex.yaml, tests/test_mlhandler.py
This commit fixes a bug in the sklearn pipeline created by MLHandler,
which was breaking the examples on the guide. We did not have a test for
this bug earlier, adding one.
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-174)
=> GRAMEX-174 ⁃ FIX: MLHandler pipeline feature

gramex/handlers/mlhandler.py, gramex/ml_api.py, gramex/sm_api.py, gramex/transformers.py, tests/gramex.yaml, tests/test_mlhandler.py
* Install [pytorch](https://pytorch.org/get-started/locally/), [transformers](https://huggingface.co/docs/transformers/installation) and [datasets](https://huggingface.co/docs/datasets/installation).
* Use the following config:
```yaml
url:
home:
pattern: /$YAMLURL/
handler: MLHandler
kwargs:
model:
class: SentimentAnalysis
```
* Train the default model with
```bash
curl -X POST /?_action=train&target_col=label -d @train.json -H "Content-Type: application/json"
```
* Get predictions with
```bash
curl -X POST /?_action=predict -d @test.json -H "Content-Type: application/json"
```
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-190)
=> GRAMEX-190 ⁃ ENH: Sentiment analysis with Huggingface transformers

gramex/apps/logviewer/gramex.yaml, gramex/apps/logviewer/logviewer.py, gramex/config.py, gramex/data.py, testlib/test_config/__init__.py, testlib/test_config/config.template.base.yaml
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-207)
=> GRAMEX-207 ⁃ Logviewer should log to a central database

gramex/cache.py, tests/test_cache.py
When we use a Redis (or disk) cache and `gramex.cache.open('file', 'template')`, it fails to cache, since Tornado Templates are not pickle-able. In such cases, fall back to a memory cache.
=> FIX: Use fallback cache for non-pickleable objects. Fixes #584

gramex/handlers/mlhandler.py, gramex/ml_api.py, gramex/transformers.py, setup.cfg, tests/gramex.yaml, tests/test_mlhandler.py
To be merged after #535 
* Use the following spec:
```yaml
url:
home:
pattern: /$YAMLURL/
handler: MLHandler
kwargs:
config_dir: $YAMLPATH/config
xsrf_cookies: false
model:
class: NER
```
* Get predictions of individual sentences with `/?text=<sentence1>&text=<sentence2>`.
* Get bulk predictions with
```bash
curl -X POST /?_action=predict -d @data.json -H "Content-Type: application/json"
```
* Download sample data [here](https://bit.ly/3wZYsf5).
* Get scores (f1, precision and recall for each NE label) with
```bash
curl -X POST /?_action=score&target_col=labels -d @ner-train.json -H "Content-Type: application/json"
```
* Train the model with
```bash
curl -X POST /?_action=train&target_col=labels -d @ner-train.json -H "Content-Type: application/json"
```
Uploaded files here must be of the …
=> GRAMEX-200 ⁃ ENH: NER with Huggingface transformers

gramex/data.py
So if there's an OFFSET/LIMIT without a SORT BY in MSSQL, we sort it ascending by the first column.
(This may not be efficient, but it's simple.)
=> STY: MSSQL requires an ORDER BY for offset/limit to work. Fixes #626

gramex/transforms/transforms.py
When testing, it's useful to pass a non-handler object to gramex.transforms.handler, e.g.
```python
handler = AttrDict(args=...)
fn = gramex.transforms.handler(fn)(handler)
```
This is now possible.
=> REF: gramex.transforms.handler works when passed a non-handler

gramex/handlers/basehandler.py
Earlier, handler.args was not defined for WebsocketHandler. This was an oversight.
We now support handler.args for WebsocketHandlers too.
=> FIX: WebsocketHandler should support args

gramex/apps/ui/__init__.py
We cannot use shell=True to run npx, since users may enter
?format=;rm -rf *
So, when compiling TypeScript via esbuild, check if esbuild is a shell script. If yes, run it with node. Else run it as an EXE.
=> FIX: bandit security vulnerability

gramex/apps/admin2/gramexadmin.py
Currently AdminFormHandler does not use the auth: specified for ADMIN_AUTH. As a result, the admin `/user-data` is exposed publicly. This fixes that.
Also, `handler.error` is reserved for error handlers. Use `handler.error_message` for custom error messages.
=> FIX: Admin2 should not expose auth data
